# -*- coding: utf-8 -*-
"""mcdonalds-review.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/vedant-sonani/793d19a59be0397b483b609f978b798b/mcdonalds-review.ipynb

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('McDonald_s_Reviews.csv')
df.head()
"""

!pip install plotly

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

df = pd.read_csv('/content/McDonald_s_Reviews.csv', encoding='latin-1')

print(df.iloc[0])

print(df.columns)

print(df.info())
print(df.isnull().sum())

df.dropna(subset=['review', 'rating'], inplace=True)

df.drop_duplicates(subset=['review'], inplace=True)

def parse_rating(rating):
    if isinstance(rating, str):
        return int(rating.split()[0])
    return rating

df['rating'] = df['rating'].apply(parse_rating)

print(df.columns)

df = df.rename(columns={'latitude ': 'latitude'})

avg_rating_per_store = df.groupby(['store_name', 'latitude', 'longitude']).agg(
    avg_rating=('rating', 'mean'),
    rating_count=('rating', 'size')
).reset_index()

top_10_stores = avg_rating_per_store.nlargest(10, 'rating_count')

print("Top 10 stores with the highest number of ratings:")
print(top_10_stores[['store_name', 'latitude', 'longitude', 'rating_count']])

def parse_rating(rating):
    if isinstance(rating, str):
        return int(rating.split()[0])
    return rating

df['rating'] = df['rating'].apply(parse_rating)


print(df.columns)

df = df.rename(columns={'latitude ': 'latitude'})

avg_rating_per_store = df.groupby(['latitude', 'longitude'])['rating'].mean().reset_index()
avg_rating_per_store.columns = ['latitude', 'longitude', 'avg_rating']

fig = px.scatter_3d(avg_rating_per_store,
                    x='longitude',
                    y='latitude',
                    z='avg_rating',
                    color='avg_rating',
                    title='3D Visualization of Average Rating by Store Location',
                    labels={'longitude': 'Longitude', 'latitude': 'Latitude', 'avg_rating': 'Average Rating'})

fig.show()

